-- Salon Brigida POS - Supabase tablas completas
-- Pega este archivo en Supabase > SQL Editor > Run.
-- Recomendado: usarlo con Authentication activado y un usuario creado.

create table if not exists public.pos_snapshots (
  id text primary key default 'main',
  payload jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.pos_clients (
  id text primary key,
  name text not null default '',
  phone text not null default '',
  cedula text not null default '',
  email text not null default '',
  notes text not null default '',
  bday date,
  credit_limit numeric(12,2) not null default 0,
  visits integer not null default 0,
  total_spent numeric(12,2) not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.pos_products (
  id text primary key,
  name text not null default '',
  barcode text not null default '',
  price numeric(12,2) not null default 0,
  stock numeric(12,2) not null default 0,
  cat text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.pos_services (
  id text primary key,
  name text not null default '',
  price numeric(12,2) not null default 0,
  duration integer not null default 0,
  cat text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.pos_sales (
  id text primary key,
  invoice_num bigint,
  sale_date timestamptz,
  client_id text,
  client_name text,
  subtotal numeric(12,2) not null default 0,
  discount numeric(12,2) not null default 0,
  bday_discount numeric(12,2) not null default 0,
  adjustment numeric(12,2) not null default 0,
  adjust_reason text,
  total numeric(12,2) not null default 0,
  method text,
  cash_received numeric(12,2),
  change_amount numeric(12,2),
  paid_amount numeric(12,2) not null default 0,
  balance_due numeric(12,2) not null default 0,
  payment_status text not null default 'paid',
  updated_at timestamptz not null default now()
);

create table if not exists public.pos_sale_items (
  id bigint generated by default as identity primary key,
  sale_id text not null references public.pos_sales(id) on delete cascade,
  item_id text,
  name text not null default '',
  price numeric(12,2) not null default 0,
  qty numeric(12,2) not null default 0,
  item_type text not null default '',
  cat text not null default ''
);

create index if not exists pos_sale_items_sale_id_idx
  on public.pos_sale_items (sale_id);

create table if not exists public.pos_sale_payments (
  id text primary key,
  sale_id text not null references public.pos_sales(id) on delete cascade,
  pay_date timestamptz,
  amount numeric(12,2) not null default 0,
  method text not null default '',
  note text not null default ''
);

create index if not exists pos_sale_payments_sale_id_idx
  on public.pos_sale_payments (sale_id);

create table if not exists public.pos_turns (
  id text primary key,
  turn_num integer,
  client_id text,
  name text not null default '',
  status text not null default 'waiting',
  created_at timestamptz,
  services jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.pos_caja_current (
  id text primary key default 'current',
  opened timestamptz,
  fondo_inicial numeric(12,2) not null default 0,
  movimientos jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.pos_caja_history (
  id text primary key,
  opened timestamptz,
  closed_at timestamptz,
  fondo_inicial numeric(12,2) not null default 0,
  movimientos jsonb not null default '[]'::jsonb,
  cash_in numeric(12,2) not null default 0,
  change_out numeric(12,2) not null default 0,
  expected numeric(12,2) not null default 0,
  total_all numeric(12,2) not null default 0,
  tx_all integer not null default 0,
  tx_card numeric(12,2) not null default 0,
  tx_trans numeric(12,2) not null default 0,
  movs_in numeric(12,2) not null default 0,
  movs_out numeric(12,2) not null default 0,
  conteo numeric(12,2) not null default 0,
  diff numeric(12,2) not null default 0,
  obs text not null default '',
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create or replace view public.pos_accounts_receivable as
select
  coalesce(s.client_id, 'sale-' || s.id) as receivable_id,
  max(coalesce(c.name, s.client_name, 'Cliente sin ficha')) as client_name,
  max(coalesce(c.phone, '')) as phone,
  count(*) as open_invoices,
  sum(s.balance_due) as total_due,
  min(s.sale_date) as oldest_sale_date,
  max(s.sale_date) as latest_sale_date
from public.pos_sales s
left join public.pos_clients c on c.id = s.client_id
where s.balance_due > 0
group by coalesce(s.client_id, 'sale-' || s.id);

alter table public.pos_snapshots enable row level security;
alter table public.pos_clients enable row level security;
alter table public.pos_products enable row level security;
alter table public.pos_services enable row level security;
alter table public.pos_sales enable row level security;
alter table public.pos_sale_items enable row level security;
alter table public.pos_sale_payments enable row level security;
alter table public.pos_turns enable row level security;
alter table public.pos_caja_current enable row level security;
alter table public.pos_caja_history enable row level security;

drop policy if exists "Salon Brigida authenticated all snapshots" on public.pos_snapshots;
drop policy if exists "Salon Brigida authenticated all clients" on public.pos_clients;
drop policy if exists "Salon Brigida authenticated all products" on public.pos_products;
drop policy if exists "Salon Brigida authenticated all services" on public.pos_services;
drop policy if exists "Salon Brigida authenticated all sales" on public.pos_sales;
drop policy if exists "Salon Brigida authenticated all sale items" on public.pos_sale_items;
drop policy if exists "Salon Brigida authenticated all sale payments" on public.pos_sale_payments;
drop policy if exists "Salon Brigida authenticated all turns" on public.pos_turns;
drop policy if exists "Salon Brigida authenticated all caja current" on public.pos_caja_current;
drop policy if exists "Salon Brigida authenticated all caja history" on public.pos_caja_history;

create policy "Salon Brigida authenticated all snapshots"
  on public.pos_snapshots for all to authenticated
  using (true) with check (true);

create policy "Salon Brigida authenticated all clients"
  on public.pos_clients for all to authenticated
  using (true) with check (true);

create policy "Salon Brigida authenticated all products"
  on public.pos_products for all to authenticated
  using (true) with check (true);

create policy "Salon Brigida authenticated all services"
  on public.pos_services for all to authenticated
  using (true) with check (true);

create policy "Salon Brigida authenticated all sales"
  on public.pos_sales for all to authenticated
  using (true) with check (true);

create policy "Salon Brigida authenticated all sale items"
  on public.pos_sale_items for all to authenticated
  using (true) with check (true);

create policy "Salon Brigida authenticated all sale payments"
  on public.pos_sale_payments for all to authenticated
  using (true) with check (true);

create policy "Salon Brigida authenticated all turns"
  on public.pos_turns for all to authenticated
  using (true) with check (true);

create policy "Salon Brigida authenticated all caja current"
  on public.pos_caja_current for all to authenticated
  using (true) with check (true);

create policy "Salon Brigida authenticated all caja history"
  on public.pos_caja_history for all to authenticated
  using (true) with check (true);

grant select, insert, update, delete on table public.pos_snapshots to authenticated;
grant select, insert, update, delete on table public.pos_clients to authenticated;
grant select, insert, update, delete on table public.pos_products to authenticated;
grant select, insert, update, delete on table public.pos_services to authenticated;
grant select, insert, update, delete on table public.pos_sales to authenticated;
grant select, insert, update, delete on table public.pos_sale_items to authenticated;
grant select, insert, update, delete on table public.pos_sale_payments to authenticated;
grant select, insert, update, delete on table public.pos_turns to authenticated;
grant select, insert, update, delete on table public.pos_caja_current to authenticated;
grant select, insert, update, delete on table public.pos_caja_history to authenticated;
grant select on table public.pos_accounts_receivable to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into public.pos_snapshots (id, payload)
values ('main', '{"version":"10.21","db":{"clients":[],"products":[],"services":[],"sales":[]}}'::jsonb)
on conflict (id) do nothing;
